version: 2
jobs:
  build-dynamic:
    docker:
      - image: circleci/buildpack-deps:xenial
    working_directory: ~/Linda
    steps:
      - checkout
      - run:
          shell: /bin/bash
          name: Get build environment ready
          command: |
            sudo apt install -y build-essential libtool automake autotools-dev autoconf pkg-config libssl-dev libgmp3-dev libevent-dev bsdmainutils software-properties-common
            sudo apt install -y libboost-system-dev libboost-filesystem-dev libboost-chrono-dev libboost-program-options-dev libboost-test-dev libboost-thread-dev
            sudo add-apt-repository -y ppa:bitcoin/bitcoin
            sudo apt update
            sudo apt install -y libdb4.8-dev libdb4.8++-dev
            sudo apt install -y libminiupnpc-dev
      - run:
          shell: /bin/bash
          name: Build Lindad
          command: |
            echo "Build Lindad"
            cd ~/Linda
            chmod +x autogen.sh
            chmod +x share/genbuild.sh
            chmod +x src/leveldb/build_detect_platform
            chmod -R 775 src/leveldb
            ./autogen.sh
            ./configure --with-boost-libdir=/usr/lib/x86_64-linux-gnu
            make
            ll src/Linda*
  build-static:
    docker:
      - image: circleci/buildpack-deps:xenial
    working_directory: ~/Linda
    steps:
      - checkout
      - run:
          shell: /bin/bash
          name: Get build environment ready
          command: |
            sudo apt install -y build-essential libtool automake autotools-dev autoconf pkg-config libssl-dev libgmp3-dev libevent-dev bsdmainutils
            mkdir -p ~/deps
      - run:
          shell: /bin/bash
          name: Build Dependancies
          command: |
            cd ~/Linda/depends
            make NO_QT=1
      - run:
          shell: /bin/bash
          name: Build Lindad
          command: |
            echo "Build Lindad"
            cd ~/Linda
            ./autogen.sh
            ./configure --prefix=`pwd`/depends/x86_64-unknown-linux-gnu
            make
            ll src/Linda*

workflows:
  version: 2
  commits:
    jobs:
      - build-dynamic
  nightly:
    triggers:
      - schedule:
          cron: "00 12 * * 0"
          filters:
            branches:
              only:
                - master
                - /(v|V)\d.\d.\d.\d.*/
    jobs:
      - build-static
