version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:xenial
    working_directory: ~/Linda
    steps:
      - checkout
      - run:
          shell: /bin/bash
          name: Get build environment ready
          command: |
            sudo apt install -y build-essential libtool automake autotools-dev autoconf pkg-config libssl-dev libgmp3-dev libevent-dev bsdmainutils
            mkdir -p ~/deps
      - run:
          shell: /bin/bash
          name: Build BerkeleyDB
          command: |
            cd ~/deps
            wget 'http://download.oracle.com/berkeley-db/db-5.0.32.NC.tar.gz'
            tar -xzvf db-5.0.32.NC.tar.gz
            cd db-5.0.32.NC/build_unix/
            ../dist/configure --enable-cxx --disable-shared 
            make
      - run:
          shell: /bin/bash
          name: Build Boost 1.58
          command: |
            cd ~/deps
            wget -O boost_1_58_0.tar.gz https://sourceforge.net/projects/boost/files/boost/1.58.0/boost_1_58_0.tar.gz/download
            tar xvfz boost_1_58_0.tar.gz
            cd ~/deps/boost_1_58_0
            ./bootstrap.sh
            ./b2 --build-type=complete --layout=versioned --with-chrono --with-filesystem --with-program_options --with-system --with-thread toolset=gcc variant=release link=static threading=multi runtime-link=static stage
      - run:
          shell: /bin/bash
          name: Build miniupnpc 1.9
          command: |
            cd ~/deps
            wget -O miniupnpc-1.9.tar.gz http://miniupnp.free.fr/files/download.php?file=miniupnpc-1.9.tar.gz
            tar xvzf miniupnpc-1.9.tar.gz
            mv miniupnpc-1.9 miniupnpc
            cd miniupnpc
            make upnpc-static
      - run:
          shell: /bin/bash
          name: Build Openssl 1.0.2g
          command: |
            cd ~/deps
            wget -O openssl-1.0.2g.tar.gz https://www.openssl.org/source/old/1.0.2/openssl-1.0.2g.tar.gz
            tar xvfz openssl-1.0.2g.tar.gz
            cd openssl-1.0.2g 
            ./config no-shared no-dso
            make depend
            make
      - run:
          shell: /bin/bash
          name: Build leveldb
          command: |
            echo "Build leveldb"
            cd ~/Linda/src/leveldb
            chmod +x build_detect_platform
            chmod 775 *
            make libleveldb.a libmemenv.a
      - run:
          shell: /bin/bash
          name: Build libsecp256k1
          command: |
            echo "Build libsecp256k1"
            cd ~/Linda/src/secp256k1
            ./autogen.sh
            ./configure --enable-static --disable-shared
            make
      - run:
          shell: /bin/bash
          name: Build Lindad
          command: |
            echo "Build Lindad"
            cd ~/Linda/src
            echo "DEPS_PATH = \$(HOME)/deps" > static.build
            echo "SECP256K1_LIB_PATH = src/secp256k1/.libs" >> static.build
            echo "SECP256K1_INCLUDE_PATH = src/secp256k1/include" >> static.build
            echo "MINIUPNPC_LIB_PATH = \$(DEPS_PATH)/miniupnpc" >> static.build
            echo "MINIUPNPC_INCLUDE_PATH = \$(DEPS_PATH)" >> static.build
            echo "BOOST_LIB_SUFFIX = -gcc54-mt-s-1_58" >> static.build
            echo "BOOST_LIB_PATH = \$(DEPS_PATH)/boost_1_58_0/stage/lib" >> static.build
            echo "BOOST_INCLUDE_PATH = \$(DEPS_PATH)/boost_1_58_0" >> static.build
            echo "BDB_LIB_PATH = \$(DEPS_PATH)/db-5.0.32.NC/build_unix" >> static.build
            echo "BDB_INCLUDE_PATH = \$(DEPS_PATH)/db-5.0.32.NC/build_unix" >> static.build
            echo "OPENSSL_LIB_PATH = \$(DEPS_PATH)/openssl-1.0.2g" >> static.build
            echo "OPENSSL_INCLUDE_PATH = \$(DEPS_PATH)/openssl-1.0.2g/include" >> static.build
            cat static.build makefile.unix > makefile_static.unix
            make -f makefile_static.unix STATIC=1
            strip ./Lindad

workflows:
  version: 2
  build_lindad:
    jobs:
      - build:
          filters:
            branches:
              only: V3.2.0.0-dev